-- 创建签到表
create table if not exists checkins (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  device text,
  session text,
  timestamp text
);

-- 启用行级安全策略（虽然我们使用 service role key 可以绕过，但为了安全最好开启）
alter table checkins enable row level security;

-- 创建策略：允许匿名用户（拥有 anon key）插入数据
create policy "Enable insert for anon" on checkins for insert with check (true);

-- 创建策略：允许匿名用户读取所有数据（或者你可以限制只能读取特定 session 的数据）
create policy "Enable select for anon" on checkins for select using (true);

-- 创建策略：允许匿名用户删除数据（用于重置功能）
create policy "Enable delete for anon" on checkins for delete using (true);
